apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: washflow-local
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mayconaraujosantos/washflow-app.git
    targetRevision: develop
    path: infra/k8s/local
  destination:
    server: https://kubernetes.default.svc
    namespace: washflow-local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
